/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionIndexRouteImport } from './routes/collection.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection': typeof CollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/lookbook': typeof LookbookRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collection/': typeof CollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/lookbook'
    | '/search'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$slug'
    | '/collection/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/lookbook'
    | '/search'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$slug'
    | '/collection'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/cart'
    | '/contact'
    | '/lookbook'
    | '/search'
    | '/wishlist'
    | '/collection/$slug'
    | '/product/$slug'
    | '/collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  LookbookRoute: typeof LookbookRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  LookbookRoute: LookbookRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
